# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timer.int.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='timer.int.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ftimer.int.proto\x12\x02pb\"\x0e\n\x0cTimerTestReq\"\x0e\n\x0cTimerTestRes\"\x1d\n\x1b\x41\x64\x64\x41strologyLotteryTimerReq\"\x1d\n\x1b\x41\x64\x64\x41strologyLotteryTimerRes\"\x17\n\x15\x41\x64\x64NumLotteryTimerReq\"\x17\n\x15\x41\x64\x64NumLotteryTimerRes\"\x18\n\x16\x41\x64\x64SlotMachineTimerReq\"\x18\n\x16\x41\x64\x64SlotMachineTimerRes\"3\n\x11\x41\x64\x64PkteamTimerReq\x12\x0e\n\x06pk_num\x18\x01 \x01(\x03\x12\x0e\n\x06\x65nd_at\x18\x02 \x01(\x03\"\x13\n\x11\x41\x64\x64PkteamTimerRes2\xf2\x02\n\x0bTimerIntObj\x12*\n\x04Test\x12\x10.pb.TimerTestReq\x1a\x10.pb.TimerTestRes\x12\\\n\x18\x41\x64\x64\x41strologyLotteryTimer\x12\x1f.pb.AddAstrologyLotteryTimerReq\x1a\x1f.pb.AddAstrologyLotteryTimerRes\x12J\n\x12\x41\x64\x64NumLotteryTimer\x12\x19.pb.AddNumLotteryTimerReq\x1a\x19.pb.AddNumLotteryTimerRes\x12>\n\x0e\x41\x64\x64PkteamTimer\x12\x15.pb.AddPkteamTimerReq\x1a\x15.pb.AddPkteamTimerRes\x12M\n\x13\x41\x64\x64SlotMachineTimer\x12\x1a.pb.AddSlotMachineTimerReq\x1a\x1a.pb.AddSlotMachineTimerResb\x06proto3')
)




_TIMERTESTREQ = _descriptor.Descriptor(
  name='TimerTestReq',
  full_name='pb.TimerTestReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=37,
)


_TIMERTESTRES = _descriptor.Descriptor(
  name='TimerTestRes',
  full_name='pb.TimerTestRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=53,
)


_ADDASTROLOGYLOTTERYTIMERREQ = _descriptor.Descriptor(
  name='AddAstrologyLotteryTimerReq',
  full_name='pb.AddAstrologyLotteryTimerReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=84,
)


_ADDASTROLOGYLOTTERYTIMERRES = _descriptor.Descriptor(
  name='AddAstrologyLotteryTimerRes',
  full_name='pb.AddAstrologyLotteryTimerRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=115,
)


_ADDNUMLOTTERYTIMERREQ = _descriptor.Descriptor(
  name='AddNumLotteryTimerReq',
  full_name='pb.AddNumLotteryTimerReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=140,
)


_ADDNUMLOTTERYTIMERRES = _descriptor.Descriptor(
  name='AddNumLotteryTimerRes',
  full_name='pb.AddNumLotteryTimerRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=165,
)


_ADDSLOTMACHINETIMERREQ = _descriptor.Descriptor(
  name='AddSlotMachineTimerReq',
  full_name='pb.AddSlotMachineTimerReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=191,
)


_ADDSLOTMACHINETIMERRES = _descriptor.Descriptor(
  name='AddSlotMachineTimerRes',
  full_name='pb.AddSlotMachineTimerRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=217,
)


_ADDPKTEAMTIMERREQ = _descriptor.Descriptor(
  name='AddPkteamTimerReq',
  full_name='pb.AddPkteamTimerReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pk_num', full_name='pb.AddPkteamTimerReq.pk_num', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_at', full_name='pb.AddPkteamTimerReq.end_at', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=270,
)


_ADDPKTEAMTIMERRES = _descriptor.Descriptor(
  name='AddPkteamTimerRes',
  full_name='pb.AddPkteamTimerRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=291,
)

DESCRIPTOR.message_types_by_name['TimerTestReq'] = _TIMERTESTREQ
DESCRIPTOR.message_types_by_name['TimerTestRes'] = _TIMERTESTRES
DESCRIPTOR.message_types_by_name['AddAstrologyLotteryTimerReq'] = _ADDASTROLOGYLOTTERYTIMERREQ
DESCRIPTOR.message_types_by_name['AddAstrologyLotteryTimerRes'] = _ADDASTROLOGYLOTTERYTIMERRES
DESCRIPTOR.message_types_by_name['AddNumLotteryTimerReq'] = _ADDNUMLOTTERYTIMERREQ
DESCRIPTOR.message_types_by_name['AddNumLotteryTimerRes'] = _ADDNUMLOTTERYTIMERRES
DESCRIPTOR.message_types_by_name['AddSlotMachineTimerReq'] = _ADDSLOTMACHINETIMERREQ
DESCRIPTOR.message_types_by_name['AddSlotMachineTimerRes'] = _ADDSLOTMACHINETIMERRES
DESCRIPTOR.message_types_by_name['AddPkteamTimerReq'] = _ADDPKTEAMTIMERREQ
DESCRIPTOR.message_types_by_name['AddPkteamTimerRes'] = _ADDPKTEAMTIMERRES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimerTestReq = _reflection.GeneratedProtocolMessageType('TimerTestReq', (_message.Message,), dict(
  DESCRIPTOR = _TIMERTESTREQ,
  __module__ = 'timer.int_pb2'
  # @@protoc_insertion_point(class_scope:pb.TimerTestReq)
  ))
_sym_db.RegisterMessage(TimerTestReq)

TimerTestRes = _reflection.GeneratedProtocolMessageType('TimerTestRes', (_message.Message,), dict(
  DESCRIPTOR = _TIMERTESTRES,
  __module__ = 'timer.int_pb2'
  # @@protoc_insertion_point(class_scope:pb.TimerTestRes)
  ))
_sym_db.RegisterMessage(TimerTestRes)

AddAstrologyLotteryTimerReq = _reflection.GeneratedProtocolMessageType('AddAstrologyLotteryTimerReq', (_message.Message,), dict(
  DESCRIPTOR = _ADDASTROLOGYLOTTERYTIMERREQ,
  __module__ = 'timer.int_pb2'
  # @@protoc_insertion_point(class_scope:pb.AddAstrologyLotteryTimerReq)
  ))
_sym_db.RegisterMessage(AddAstrologyLotteryTimerReq)

AddAstrologyLotteryTimerRes = _reflection.GeneratedProtocolMessageType('AddAstrologyLotteryTimerRes', (_message.Message,), dict(
  DESCRIPTOR = _ADDASTROLOGYLOTTERYTIMERRES,
  __module__ = 'timer.int_pb2'
  # @@protoc_insertion_point(class_scope:pb.AddAstrologyLotteryTimerRes)
  ))
_sym_db.RegisterMessage(AddAstrologyLotteryTimerRes)

AddNumLotteryTimerReq = _reflection.GeneratedProtocolMessageType('AddNumLotteryTimerReq', (_message.Message,), dict(
  DESCRIPTOR = _ADDNUMLOTTERYTIMERREQ,
  __module__ = 'timer.int_pb2'
  # @@protoc_insertion_point(class_scope:pb.AddNumLotteryTimerReq)
  ))
_sym_db.RegisterMessage(AddNumLotteryTimerReq)

AddNumLotteryTimerRes = _reflection.GeneratedProtocolMessageType('AddNumLotteryTimerRes', (_message.Message,), dict(
  DESCRIPTOR = _ADDNUMLOTTERYTIMERRES,
  __module__ = 'timer.int_pb2'
  # @@protoc_insertion_point(class_scope:pb.AddNumLotteryTimerRes)
  ))
_sym_db.RegisterMessage(AddNumLotteryTimerRes)

AddSlotMachineTimerReq = _reflection.GeneratedProtocolMessageType('AddSlotMachineTimerReq', (_message.Message,), dict(
  DESCRIPTOR = _ADDSLOTMACHINETIMERREQ,
  __module__ = 'timer.int_pb2'
  # @@protoc_insertion_point(class_scope:pb.AddSlotMachineTimerReq)
  ))
_sym_db.RegisterMessage(AddSlotMachineTimerReq)

AddSlotMachineTimerRes = _reflection.GeneratedProtocolMessageType('AddSlotMachineTimerRes', (_message.Message,), dict(
  DESCRIPTOR = _ADDSLOTMACHINETIMERRES,
  __module__ = 'timer.int_pb2'
  # @@protoc_insertion_point(class_scope:pb.AddSlotMachineTimerRes)
  ))
_sym_db.RegisterMessage(AddSlotMachineTimerRes)

AddPkteamTimerReq = _reflection.GeneratedProtocolMessageType('AddPkteamTimerReq', (_message.Message,), dict(
  DESCRIPTOR = _ADDPKTEAMTIMERREQ,
  __module__ = 'timer.int_pb2'
  # @@protoc_insertion_point(class_scope:pb.AddPkteamTimerReq)
  ))
_sym_db.RegisterMessage(AddPkteamTimerReq)

AddPkteamTimerRes = _reflection.GeneratedProtocolMessageType('AddPkteamTimerRes', (_message.Message,), dict(
  DESCRIPTOR = _ADDPKTEAMTIMERRES,
  __module__ = 'timer.int_pb2'
  # @@protoc_insertion_point(class_scope:pb.AddPkteamTimerRes)
  ))
_sym_db.RegisterMessage(AddPkteamTimerRes)



_TIMERINTOBJ = _descriptor.ServiceDescriptor(
  name='TimerIntObj',
  full_name='pb.TimerIntObj',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=294,
  serialized_end=664,
  methods=[
  _descriptor.MethodDescriptor(
    name='Test',
    full_name='pb.TimerIntObj.Test',
    index=0,
    containing_service=None,
    input_type=_TIMERTESTREQ,
    output_type=_TIMERTESTRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddAstrologyLotteryTimer',
    full_name='pb.TimerIntObj.AddAstrologyLotteryTimer',
    index=1,
    containing_service=None,
    input_type=_ADDASTROLOGYLOTTERYTIMERREQ,
    output_type=_ADDASTROLOGYLOTTERYTIMERRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddNumLotteryTimer',
    full_name='pb.TimerIntObj.AddNumLotteryTimer',
    index=2,
    containing_service=None,
    input_type=_ADDNUMLOTTERYTIMERREQ,
    output_type=_ADDNUMLOTTERYTIMERRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddPkteamTimer',
    full_name='pb.TimerIntObj.AddPkteamTimer',
    index=3,
    containing_service=None,
    input_type=_ADDPKTEAMTIMERREQ,
    output_type=_ADDPKTEAMTIMERRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AddSlotMachineTimer',
    full_name='pb.TimerIntObj.AddSlotMachineTimer',
    index=4,
    containing_service=None,
    input_type=_ADDSLOTMACHINETIMERREQ,
    output_type=_ADDSLOTMACHINETIMERRES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TIMERINTOBJ)

DESCRIPTOR.services_by_name['TimerIntObj'] = _TIMERINTOBJ

# @@protoc_insertion_point(module_scope)
